Add support for Timer control on GPIO P05 for BLENano2
foundriesio/dm-lwm2m-light pull request #5
Opened 2019-02-08 21:17 UTC by mike-scott

Now that Zephyr supports IPSO Timer object, let's use it on
GPIO P05 (set via DTS in boards/nrf52_blenano2.overlay)
to support Candy Machine / Drink Dispenser.

Signed-off-by: Michael Scott <mike@foundries.io>

2019-02-08 21:18 UTC, mike-scott commented
NOTE: Requires https://github.com/foundriesio/zephyr/pull/4

2019-02-11 17:24 UTC, mbolivar requested changes
I'm not against this change, but I don't think this app should continue to be part of our manifest if we're going to continue to extend it for demos. It's much more than a light now.

2019-02-11 18:24 UTC, mbolivar reviewed
x

2019-02-11 18:25 UTC, mbolivar approved these changes

2019-02-11 18:25 UTC, merged